[project]
name = "real-time-recommendation"
version = "0.1.0"
description = "real time recommendation system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kafka-python>=2.3.0",
    "numpy>=2.4.0",
    "pyspark>=4.1.0",
]
